//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_autoparking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public int account_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> employee_id { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
