//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_autoparking
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoParkEntities : DbContext
    {
        public AutoParkEntities()
            : base("name=AutoParkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<CarCategories> CarCategories { get; set; }
        public virtual DbSet<CarCategoryMappings> CarCategoryMappings { get; set; }
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<InsurancePolicies> InsurancePolicies { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<RentalHistory> RentalHistory { get; set; }
        public virtual DbSet<Rentals> Rentals { get; set; }
        public virtual DbSet<CarDamageHistory> CarDamageHistory { get; set; }
        public virtual DbSet<CarWithCategories> CarWithCategories { get; set; }
        public virtual DbSet<TopEmployeeRentals> TopEmployeeRentals { get; set; }
    }
}
