//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_autoparking
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarCategoryMappings
    {
        public int car_id { get; set; }
        public int category_id { get; set; }
        public int mapping_id { get; set; }
    
        public virtual CarCategories CarCategories { get; set; }
        public virtual Cars Cars { get; set; }
    }
}
