//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_autoparking
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarWithCategories
    {
        public string Марка { get; set; }
        public string Модель { get; set; }
        public int Год { get; set; }
        public string Цвет { get; set; }
        public decimal Цена_за_сутки { get; set; }
        public string Адрес { get; set; }
        public string Categories { get; set; }
    }
}
