//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_autoparking
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalHistory
    {
        public int rental_history_id { get; set; }
        public int rental_id { get; set; }
        public string damage_description { get; set; }
        public string customer_comments { get; set; }
    
        public virtual Rentals Rentals { get; set; }
    }
}
